name: 浏览器访问

on:
  schedule:
    - cron: '*/1 * * * *'  # 每5分钟执行一次
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests webdriver_manager

      - name: 下载并设置 ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb
          wget -N https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver

      - name: 运行python脚本
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python visite.py
